@echo off
echo Restoring Jumbee.Console...
dotnet restore src\Jumbee.Console.sln
if errorlevel 1 exit /b 1
echo Building Jumbee.Console and example projects in Release configuration...
echo Building Jumbee.Console library...
dotnet build src\Jumbee.Console\Jumbee.Console.csproj /p:Configuration=Release
echo Building examples browser...
dotnet build examples\Jumbee.Console.Examples\Jumbee.Console.Examples.csproj /p:Configuration=Release
if errorlevel 1 exit /b 1
echo Building agent harness demo...
dotnet build examples\Jumbee.Console.AgentHarnessDemo\Jumbee.Console.AgentHarnessDemo.csproj /p:Configuration=Release
if errorlevel 1 exit /b 1
echo Building IDE demo...
dotnet build examples\Jumbee.Console.IdeDemo\Jumbee.Console.IdeDemo.csproj /p:Configuration=Release
if errorlevel 1 exit /b 1
echo Building audio scope demo...
dotnet build examples\Jumbee.Console.AudioScopeDemo\Jumbee.Console.AudioScopeDemo.csproj /p:Configuration=Release
if errorlevel 1 exit /b 1
echo Building 3D sandbox demo...
dotnet build examples\Jumbee.Console.3DSandboxDemo\Jumbee.Console.3DSandboxDemo.csproj /p:Configuration=Release
if errorlevel 1 exit /b 1
echo Jumbee.Console build complete.
