<#
.SYNOPSIS
    Assembles a local "published-world" snapshot so the jc-curious agent (or you) can test doc/package
    changes WITHOUT running the real publish pipeline (no nuget.org push, no git push).

.DESCRIPTION
    Produces, OUTSIDE the repo, a folder containing:
      * feed\         - the three packages, packed at a unique prerelease version (so NuGet never serves a
                        stale cached copy and the local feed wins over nuget.org).
      * docs\         - a mirror of ONLY the public doc surface (repo-root READMEs, docs\{api,controls,
                        getting-started}, package\*.md). It deliberately EXCLUDES docs\internal, CLAUDE.md,
                        GEMINI.md, src\, ext\ — so an agent pointed here sees exactly what a real user sees.
      * nuget.config  - restores from feed\ first, then nuget.org (for NTokenizers/AdocNet/etc.).
      * PREVIEW.txt   - the version + how to consume it.

    Point jc-curious at this folder ("preview mode"): her docs are docs\, her package feed is feed\, and she
    never touches the repo. The published-world isolation is enforced by what's copied here, not by trust.

.PARAMETER Output
    Where to build the snapshot. Default: <user profile>\jc-preview (outside the repo on purpose).

.PARAMETER SkipPack
    Reuse the existing artifacts\*.nupkg instead of re-packing (faster when only docs changed — but then the
    feed keeps its previous version; bump only when code changed).

.EXAMPLE
    powershell -File preview.ps1
    powershell -File preview.ps1 -Output D:\tmp\jc-preview
#>
[CmdletBinding()]
param(
    [string] $Output = (Join-Path $env:USERPROFILE 'jc-preview'),
    [switch] $SkipPack,
    [switch] $SkipApiDocs
)

$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot

# Unique prerelease version so a re-pack is never shadowed by NuGet's per-version cache, and so this build
# uniquely resolves against the local feed rather than the published package on nuget.org.
# The base version is read from src\Directory.Build.props rather than hardcoded here — a hardcoded one silently
# goes stale after a version bump and the preview then tests the wrong version number.
$propsPath = Join-Path $repo 'src\Directory.Build.props'
$baseVersion = ([xml](Get-Content $propsPath)).SelectSingleNode('//ProjectAssemblyVersion').InnerText.Trim()
if (-not $baseVersion) { throw "Could not read ProjectAssemblyVersion from $propsPath" }
$version = "$baseVersion-preview." + (Get-Date -Format 'yyyyMMddHHmmss')

if (-not $SkipPack) {
    Write-Host "Packing preview build $version ..." -ForegroundColor Cyan
    & (Join-Path $repo 'pack.ps1') -PackageVersion $version
}

# Regenerate the Markdown API reference from the current XML docs, so doc-comment edits actually reach the
# docs\api\*.md pages the agent reads (they're generated by docfx, not hand-written). Without this, a preview
# ships stale API docs and can't verify doc changes. Skippable when only code changed.
if (-not $SkipApiDocs) {
    Write-Host "Regenerating API docs from current XML ..." -ForegroundColor Cyan
    try { & (Join-Path $repo 'build-api-docs.ps1') }
    catch { Write-Warning "API-doc regen failed ($_); preview will use the existing docs\api." }
}

# Reset the snapshot folder.
if (Test-Path $Output) { Remove-Item $Output -Recurse -Force }
$feed = Join-Path $Output 'feed'
$docs = Join-Path $Output 'docs'
New-Item -ItemType Directory -Path $feed, $docs, (Join-Path $docs 'docs') | Out-Null

# 1. Local NuGet feed.
Copy-Item (Join-Path $repo 'artifacts\*.nupkg') $feed

# 2. Public docs ONLY (allowlist — never src/, ext/, docs/internal/, CLAUDE.md, GEMINI.md).
foreach ($f in 'README.md','GETTING-STARTED.md','TROUBLESHOOTING.md','CONTRIBUTING.md','CHANGELOG.txt','docker.md') {
    Copy-Item (Join-Path $repo $f) $docs
}
Copy-Item (Join-Path $repo 'package') (Join-Path $docs 'package') -Recurse           # NuGet-page READMEs
Copy-Item (Join-Path $repo 'docs\README.md') (Join-Path $docs 'docs')
foreach ($d in 'api','controls','getting-started') {
    Copy-Item (Join-Path $repo "docs\$d") (Join-Path $docs "docs\$d") -Recurse
}
# docs\internal is intentionally NOT copied.

# 3. nuget.config: local feed first, then nuget.org for third-party deps.
@"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="jc-local" value="$feed" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
"@ | Set-Content (Join-Path $Output 'nuget.config') -Encoding utf8

# 4. Consumer note.
@"
Jumbee.Console preview snapshot
===============================
Version : $version
Feed    : $feed
Docs    : $docs   (public subset only — no src/internal)

To consume from a project:
  copy nuget.config into the project dir, then
  dotnet add package Jumbee.Console --version $version
  (Snapshot/Documents add-ons are the same version, and depend on this local core.)
"@ | Set-Content (Join-Path $Output 'PREVIEW.txt') -Encoding utf8

Write-Host ''
Write-Host "Preview world ready: $Output" -ForegroundColor Green
Write-Host "  version : $version"
Write-Host "  feed    : $feed"
Write-Host "  docs    : $docs  (public subset only)"
Write-Host "Run jc-curious in preview mode against these two paths."
